spring:
  application:
    name: tcc
  datasource:
    url: jdbc:mysql://localhost:3306/tcc
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  private:
    key: "classpath:chave_privada.key"
  public:
    key: "classpath:chave_publica.pub"